{
  "RFE_7088_DTC_MANUAL_FAILBACK.py::RFE_7088_DTC_MANUAL_FAILBACK::test_003_create_New_AuthZone": true
}